language: php
php:
  - '7.1'

sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - docker-compose build
  - docker compose up -d
  - docker exec -it cqrs-dev "composer install --ignore-platform-reqs"

script:
  - docker exec -it cqrs-dev "vendor/bin/phpunit"