language: php
php:
  - '7.1'

sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - docker-compose build
  - docker-compose up -d
  - composer install --ignore-platform-reqs

script:
  - docker-compose -T php "vendor/bin/phpunit"