language: php
php:
  - '7.1'

sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - docker-compose -f tests/docker-compose.yml build
  - docker-compose -f tests/docker-compose.yml up -d
  - composer install --ignore-platform-reqs

script:
  - docker-compose -f tests/docker-compose.yml exec -T php "vendor/bin/phpunit"
  - docker-compose -f tests/docker-compose.yml exec -T php phpcs src --standard=PSR2