version: '2'

volumes:
  mongo_data:
    driver: local

services:
    php:
        build:
            context: docker/php
            args:
                username: ${USERNAME}
                user_id: ${USER_ID}
        volumes:
            - .:/var/www/project
        tty: true
        hostname: php
        networks:
          - cqrs
          - default
        container_name: cqrs-dev
        env_file: common.env
        entrypoint:
          - php
          - server.php
        labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:api.cqrs.dev"
          - "traefik.port=1337"
          - "traefik.protocol=http"
          - "traefik.docker.network=api_default"

    redis:
        image: redis:latest
        container_name: cqrs-redis
        ports:
            - "6379:6379"

    mongo:
        image: mongo:3.4
        container_name: cqrs-mongo
        ports:
            - "27017:27017"

    proxy:
        build:
            context: docker/proxy
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - cqrs
        command: --web --docker --docker.domain=cqrs.dev --docker.exposedbydefault=false --logLevel=DEBUG

networks:
  default:
    driver: bridge
  cqrs:
    external:
      name: api_default

