version: '2'

volumes:
  mongo_data:
    driver: local

services:
    php:
        build:
            context: docker/php
            args:
                username: ${USERNAME}
                user_id: ${USER_ID}
        volumes:
            - .:/var/www/project
        tty: true
        hostname: php
        container_name: cqrs-dev
        env_file: common.env

    redis:
        image: redis:latest
        container_name: cqrs-redis

    mongo:
        image: mongo:3.4
        container_name: cqrs-mongo