user:
    endpoints:
        register:
            method: POST
            uri: /
            handler:
                id: account.service.user.register
                method: register
            middleware:
                before:
                    - common.middleware.guest: ~
        get:
            method: GET
            uri: /{id}
            handler:
                id: account.service.user.find
                method: find

healthcheck:
    endpoints:
        check:
            method: GET
            uri: /
            handler:
                id: common.service.healthcheck
                method: check