user:
    endpoints:
        register:
            method: POST
            uri: /
            handler:
                id: account.service.user.register
                method: register
            middleware:
                before:
                    - common.middleware.guest: ~