services:
    account.service.user.register:
        class: TijmenWierenga\Project\Account\Application\Service\User\RegisterUserService
        arguments: ["@account.user.repository", "@account.user.data_store", "@account.user.data_transformer", "@account.user.password_factory"]

    account.user.data_transformer:
        class: TijmenWierenga\Project\Account\Application\DataTransformer\User\UserDTODataTransformer

    timesheets.worklog.repository:
        class: TijmenWierenga\Project\Timesheets\Infrastructure\Repository\WorkLog\EventSourcedWorkLogRepository
        arguments: ["@common.event_store"]

    account.user.repository:
        class: TijmenWierenga\Project\Account\Infrastructure\Repository\User\EventSourcedUserRepository
        arguments: ["@common.event_store", "@common.projector"]

    account.user.password_factory:
        class: TijmenWierenga\Project\Account\Infrastructure\Service\User\BcryptUserPasswordFactory

    account.user.data_store:
        class: TijmenWierenga\Project\Account\Infrastructure\DataStore\Mongo\UserDataStore
        arguments: ["@common.mongo.client"]

    account.projection.user_was_created:
        class: TijmenWierenga\Project\Account\Infrastructure\Projection\Mongo\User\UserWasCreatedProjection
        arguments: ["@common.mongo.client"]
        tags:
            - { name: projection }

    common.projector:
        class: TijmenWierenga\Project\Common\Infrastructure\Projection\Projector

    common.event_store:
        class: TijmenWierenga\Project\Common\Infrastructure\Event\RedisEventStore
        autowire: true
        arguments: ["@common.redis.client", "@common.serializer"]

    common.event.persister:
        class: TijmenWierenga\Project\Common\Infrastructure\Event\Subscriber\PersistDomainEventSubscriber
        arguments: ["@common.persisting_event_store"]

    common.persisting_event_store:
        class: TijmenWierenga\Project\Common\Infrastructure\Event\MongoPersistingEventStore
        arguments: ["@common.mongo.client", "@common.serializer"]

    common.event.logger:
        class: TijmenWierenga\Project\Common\Infrastructure\Event\Subscriber\LogEventSubscriber
        arguments: ["@common.logger"]
        tags:
            - { name: domain_event.subscriber }

    common.redis.client:
        class: Predis\Client
        arguments: ["%redis_config%"]

    common.mongo.client:
        class: MongoDB\Client
        arguments: ["%mongo_uri%"]

    common.serializer:
        class: NilPortugues\Serializer\Serializer
        arguments: ["@common.serializer.strategy"]

    common.serializer.strategy:
        class: NilPortugues\Serializer\Strategy\JsonStrategy

    common.logger:
        class: Monolog\Logger
        arguments: ["default"]

    common.monolog.stream_handler:
        class: Monolog\Handler\StreamHandler
        arguments: ["%logger_dir%", "%logger_debug_level%"]
        tags:
            - { name: logger_handler }