services:
    timesheets.worklog.repository:
        class: TijmenWierenga\Project\Timesheets\Infrastructure\Repository\WorkLog\EventSourcedWorkLogRepository
        arguments: ["@common.event_store"]

    account.user.repository:
        class: TijmenWierenga\Project\Account\Infrastructure\Repository\User\EventSourcedUserRepository
        arguments: ["@common.event_store", "@common.projector"]

    account.projection.user_was_created:
        class: TijmenWierenga\Project\Account\Infrastructure\Projection\Mongo\User\UserWasCreatedProjection
        arguments: ["@common.mongo.client"]
        tags:
            - { name: projection }

    common.projector:
        class: TijmenWierenga\Project\Common\Infrastructure\Projection\Projector

    common.event_store:
        class: TijmenWierenga\Project\Common\Infrastructure\Event\RedisEventStore
        autowire: true
        arguments: ["@common.redis.client", "@common.serializer"]

    common.redis.client:
        class: Predis\Client
        arguments: ["%redis_config%"]

    common.mongo.client:
        class: MongoDB\Client
        arguments: ["%mongo_uri%"]

    common.serializer:
        class: NilPortugues\Serializer\Serializer
        arguments: ["@common.serializer.strategy"]

    common.serializer.strategy:
        class: NilPortugues\Serializer\Strategy\JsonStrategy